name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build
        run: ./gradlew build

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: daersh/mariadb
          stage: main
          yaml: |
            name: myfunction
            app: java@17
            options:
              ports: 8010
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: prod
                - name: TODO_MYSQL_HOST
                  value: ${{ secrets.TODO_MYSQL_HOST }}
                - name: TODO_MYSQL_PORT
                  value: ${{ secrets.TODO_MYSQL_PORT }}
                - name: TODO_DATA_BASE_NAME
                  value: ${{ secrets.TODO_DATA_BASE_NAME }}
                - name: TODO_MYSQL_USER_NAME
                  value: ${{ secrets.TODO_MYSQL_USER_NAME }}
                - name: TODO_MYSQL_PASSWORD
                  value: ${{ secrets.TODO_MYSQL_PASSWORD }}
                - name: jwt_secret
                  value: ${{ secrets.JWT_SECRET }}
                - name: redis_host
                  value: ${{ secrets.REDIS_HOST }}
                - name: redis_port
                  value: ${{ secrets.REDIS_PORT }}
                - name: redis_password
                  value: ${{ secrets.REDIS_PASSWORD }}
                - name: notion_api
                  value: ${{ secrets.NOTION_API }}
                - name: mongo_host
                  value: ${{ secrets.MONGO_HOST }}
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}