name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up environment variables
        run: |
          echo "PROFILE=prod" >> $GITHUB_ENV
          echo "TODO_MYSQL_HOST=${{ secrets.TODO_MYSQL_HOST }}" >> $GITHUB_ENV
          echo "TODO_MYSQL_PORT=${{ secrets.TODO_MYSQL_PORT }}" >> $GITHUB_ENV
          echo "TODO_DATA_BASE_NAME=${{ secrets.TODO_DATA_BASE_NAME }}" >> $GITHUB_ENV
          echo "TODO_MYSQL_USER_NAME=${{ secrets.TODO_MYSQL_USER_NAME }}" >> $GITHUB_ENV
          echo "TODO_MYSQL_PASSWORD=${{ secrets.TODO_MYSQL_PASSWORD }}" >> $GITHUB_ENV
          echo "jwt_secret=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "redis_host=${{ secrets.REDIS_HOST }}" >> $GITHUB_ENV
          echo "redis_port=${{ secrets.REDIS_PORT }}" >> $GITHUB_ENV
          echo "redis_password=${{ secrets.REDIS_PASSWORD }}" >> $GITHUB_ENV
          echo "notion_api=${{ secrets.NOTION_API }}" >> $GITHUB_ENV

      - name: Build and Deploy
        run: |
          ./gradlew build
          ./gradlew bootRun
